WITH CTE AS (
	SELECT 
		CITY, 
		SUBSTRING_INDEX(GROUP_CONCAT(EMP_NAME ORDER BY EMP_NAME), ',', 3) AS EMP_NAME, 
		CONCAT ('Group', ROW_NUMBER() OVER (ORDER BY CITY)) AS Team,
		CEILING(ROW_NUMBER() OVER (ORDER BY CITY, EMP_NAME)/3) Team_Group
	FROM 
		emp_details 
GROUP BY CITY, EMP_NAME 
)
SELECT 
	CITY, 
    EMP_NAME, 
    Team_Group 
FROM 
	CTE
ORDER BY CITY ASC
LIMIT 20;